"""Type stubs for the compiled ``epigrep._core`` extension module.

These signatures mirror the pyo3 bindings in ``crates/epigrep-py/src/lib.rs``.
The compiled module is the semantic source of truth; this stub only describes
its surface to type checkers. The re-exported, supported names live in
:mod:`epigrep`; the leading-underscore matchers (``match_events`` /
``near_miss_events``) are internal — use :func:`epigrep.match` /
:func:`epigrep.explain`.
"""

from typing import Any, Optional, Union

# An event attribute or captured binding value.
Value = Union[str, int, float, bool, None]

class Event:
    def __init__(
        self,
        partition: str,
        ts: int,
        typ: str,
        attrs: Optional[dict[str, Value]] = ...,
    ) -> None: ...
    @property
    def partition(self) -> str: ...
    @property
    def ts(self) -> int: ...
    @property
    def typ(self) -> str: ...
    @property
    def attrs(self) -> dict[str, Value]: ...

class Pattern:
    @staticmethod
    def event(typ: str) -> PatternBuilder: ...
    def to_json(self, pretty: bool = ...) -> str: ...

class PatternBuilder:
    def where_eq(self, attribute: str, value: Value) -> PatternBuilder: ...
    def where_ne(self, attribute: str, value: Value) -> PatternBuilder: ...
    def where_gt(self, attribute: str, value: Value) -> PatternBuilder: ...
    def where_gte(self, attribute: str, value: Value) -> PatternBuilder: ...
    def where_lt(self, attribute: str, value: Value) -> PatternBuilder: ...
    def where_lte(self, attribute: str, value: Value) -> PatternBuilder: ...
    def capture(self, attribute: str, name: str) -> PatternBuilder: ...
    def where_ref_eq(self, attribute: str, name: str) -> PatternBuilder: ...
    def then(
        self,
        typ: str,
        within: Optional[int] = ...,
        no: Optional[str] = ...,
    ) -> PatternBuilder: ...
    def build(self) -> Pattern: ...

class Match:
    @property
    def partition(self) -> str: ...
    @property
    def indices(self) -> list[int]: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def types(self) -> list[str]: ...
    @property
    def events(self) -> list[Event]: ...
    @property
    def captures(self) -> dict[str, Value]: ...

class NearMiss:
    @property
    def partition(self) -> str: ...
    @property
    def start_index(self) -> int: ...
    @property
    def indices(self) -> list[int]: ...
    @property
    def reached_steps(self) -> int: ...
    @property
    def next_event_type(self) -> str: ...
    @property
    def reason(self) -> str: ...
    @property
    def detail(self) -> dict[str, Any]: ...
    @property
    def events(self) -> list[Event]: ...
    @property
    def captures(self) -> dict[str, Value]: ...

def parse_pattern(text: str) -> Pattern: ...
def pattern_from_json(json: str) -> Pattern: ...
def sort_events(events: list[Event]) -> list[Event]: ...
def match_events(
    pattern: Union[Pattern, PatternBuilder],
    events: list[Event],
    exhaustive: bool = ...,
    use_oracle: bool = ...,
) -> list[Match]: ...
def near_miss_events(
    pattern: Union[Pattern, PatternBuilder],
    events: list[Event],
) -> list[NearMiss]: ...
